### ISSUE TITLE
黏性头部点击时,偶然出现ArrayIndexOutOfBoundsException异常

### ISSUE THREAD

**Issue by hu499019771** [oubowu/PinnedSectionItemDecoration#15]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                               at java.util.ArrayList.get(ArrayList.java:310)
                                                                               at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getDefItemViewType(BaseMultiItemQuickAdapter.java:35)
                                                                               at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:462)
                                                                               at com.chad.library.adapter.base.listener.SimpleClickListener.isHeaderOrFooterPosition(SimpleClickListener.java:233)
                                                                               at com.chad.library.adapter.base.listener.SimpleClickListener.access$300(SimpleClickListener.java:31)
                                                                               at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onLongPress(SimpleClickListener.java:160)
                                                                               at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:809)
                                                                               at android.view.GestureDetector.access$200(GestureDetector.java:46)
                                                                               at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:305)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:158)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by hu499019771** [comment]
@oubowu 有空帮忙查看下原因吗?谢谢

**Comment by oubowu** [comment]
能提供demo吗 因为你结合了其他适配器了

**Comment by hu499019771** [comment]
之前解决了,忘记回复了,不好意思

**Comment by hu499019771** [comment]
是我这边的业务代码问题
