### ISSUE TITLE
压力测试报错

### ISSUE THREAD

**Issue by nicelyjust** [oubowu/PinnedSectionItemDecoration#46]
`STACK_TRACE=java.lang.ArrayIndexOutOfBoundsException: length=11; index=-1
	at android.util.SparseArray.keyAt(SparseArray.java:280)
	at com.oushangfeng.pinnedsectionitemdecoration.callback.OnItemTouchListener.shouldIntercept(OnItemTouchListener.java:144)
	at com.oushangfeng.pinnedsectionitemdecoration.callback.OnItemTouchListener.access$400(OnItemTouchListener.java:17)
	at com.oushangfeng.pinnedsectionitemdecoration.callback.OnItemTouchListener$GestureListener.onDoubleTap(OnItemTouchListener.java:225)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:563)
	at com.oushangfeng.pinnedsectionitemdecoration.callback.OnItemTouchListener.onInterceptTouchEvent(OnItemTouchListener.java:84)
	at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2572)
	at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2618)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
	at android.view.View.dispatchPointerEvent(View.java:10234)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4447)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4308)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3874)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4001)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3882)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4058)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3874)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3882)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6225)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6199)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6160)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6328)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:151)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by oubowu** [comment]
没设置头部view需要点击的id？？？

**Comment by nicelyjust** [comment]
@oubowu 我不需要监听头部点击事件的,用的地方
`mRv.addItemDecoration(new PinnedHeaderItemDecoration.Builder(R.integer.type_header).enableDivider(false).create());`

**Comment by oubowu** [comment]
这个是必现的吗？
