### ISSUE TITLE
bug in android support 28.0.0

### ISSUE THREAD

**Issue by xie2000** [oubowu/PinnedSectionItemDecoration#70]
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6796)
at com.oushangfeng.pinnedsectionitemdecoration.PinnedHeaderItemDecoration.createPinnedHeader(PinnedHeaderItemDecoration.java:297)
at com.oushangfeng.pinnedsectionitemdecoration.PinnedHeaderItemDecoration.onDraw(PinnedHeaderItemDecoration.java:146)
at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:4284)
at android.view.View.draw(View.java:17236)
at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
at android.view.View.updateDisplayListIfDirty(View.java:16201)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)

**Comment by oubowu** [comment]
具体描述下场景 或者提供个简单的demo 周末搞

**Comment by xie2000** [comment]
我现有的手机测试也没有这个问题,是友盟反馈的一个异常

**Comment by xie2000** [comment]
https://github.com/oubowu/PinnedSectionItemDecoration/issues/43#issue-303742676,跟这位朋友反应的问题是一样的

**Comment by shlockfan** [comment]
之前版本的在9.0上会闪退是因为canvas.clipRect只允许INTERSECT and DIFFERENCE，作者后来的版本修复了这个问题，我更新到新版的就好了，在9.0上也没什么问题了。
